### ISSUE TITLE
Xcode 26 / Swift 6.3: 'import TreeSitter' yields empty module (TSLanguage not in scope)

### ISSUE THREAD

**Issue by patr1ckzhu** [tree-sitter/tree-sitter#5523]
## Summary

On Xcode 26.4 (Swift 6.3, swiftlang-6.3.0.123.5), Swift consumers of the `TreeSitter` SPM product can `import TreeSitter` without error, but cannot reference any C declarations from `lib/include/tree_sitter/api.h` — `TSLanguage`, `TSInputEncoding`, `TSInput`, etc. all resolve to `cannot find type ... in scope`. Affects every release from 0.25.0 through 0.26.8 (latest as of writing); 0.20.x is fine.

The TreeSitter Clang module *is* loaded — Clang's own lookup tables contain the symbols (see "Evidence" below). The bug is in how Xcode 26's SwiftPM/build system surfaces the publicHeadersPath modulemap to Swift consumers, not in the C sources themselves. Notably, [`swift-tree-sitter`](https://github.com/tree-sitter/swift-tree-sitter)'s CI [pins `DEVELOPER_DIR: /Applications/Xcode_16.4.app`](https://github.com/tree-sitter/swift-tree-sitter/blob/main/.github/workflows/ci.yml), so the upstream Swift binding test matrix does not catch this regression.

## Environment

- Xcode 26.4 (Build 17E192)
- Swift 6.3 (`swift-frontend -version` → `swiftlang-6.3.0.123.5 clang-2100.0.123.102`)
- `swift-tools-version: 5.8` (matches `tree-sitter`'s own Package.swift)
- macOS host, both `iphoneos` and `iphonesimulator` destinations affected
- Reproduces with `xcodebuild` and Xcode UI; **does not reproduce with `swift build` CLI** (different SwiftPM code path — see "Why amalgamation works" below)

## Reproduction

```swift
// Package.swift
// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "Repro",
    products: [.library(name: "Repro", targets: ["Repro"])],
    dependencies: [
        .package(url: "https://github.com/tree-sitter/tree-sitter", exact: "0.26.8"),
    ],
    targets: [
        .target(name: "Repro", dependencies: [
            .product(name: "TreeSitter", package: "tree-sitter"),
        ])
    ]
)
```

```swift
// Sources/Repro/Repro.swift
import TreeSitter
public func foo() -> UnsafePointer<TSLanguage>? { nil }
```

Build inside an Xcode project (or via `xcodebuild -resolvePackageDependencies` + `xcodebuild build`) on Xcode 26.4. `import TreeSitter` succeeds, every reference to `TSLanguage` (or any other api.h type) fails with `Cannot find type 'TSLanguage' in scope`.

## Evidence the C declarations *are* in the module

Running the same compile invocation Swift uses, but as bare Clang:

```sh
$ cat > /tmp/test.c <<EOF
#include "TreeSitter.h"   // or "tree_sitter/api.h"
TSLanguage *g_lang;
EOF
$ clang -fmodules \
    -fmodule-map-file=$(SourcePackages)/checkouts/tree-sitter/lib/include/module.modulemap \
    -I $(SourcePackages)/checkouts/tree-sitter/lib/include \
    -c /tmp/test.c -o /tmp/test.o
# succeeds, produces .o
```

Asking Swift's frontend to dump the ClangImporter lookup table:

```sh
$ swift -Xfrontend -dump-clang-lookup-tables -Xcc -fmodule-map-file=... test.swift
...
<<TreeSitter lookup table>>
  TSLanguage:
    TU: TSLanguage
  TSLanguageMetadata:
    TU: TSLanguageMetadata, TSLanguageMetadata
    TSLanguageMetadata: major_version
    ...
```

`TSLanguage` appears in the lookup table (TU = top-level translation unit). Yet Swift typecheck still emits `Cannot find type 'TSLanguage' in scope` — `import TreeSitter` resolves the module name but exposes nothing.

## Why 0.20.x works on Xcode 26 but 0.25+ does not

The relevant `Package.swift` diff:

| | 0.20.9 | 0.25/0.26 |
|---|---|---|
| `sources` | `["src/lib.c"]` (single amalgamation file that `#include`s every other .c) | `["src"]` (multi-file) |
| `publicHeadersPath` | default (= `"include"`) | `"include"` (explicit) |
| `cSettings.headerSearchPath` | none | `"src"` |

Both end up generating the same modulemap (`module TreeSitter { umbrella "lib/include" export * }`). But Xcode 26's build system handles single-source-file C targets along a different path that produces a Swift-visible module, while the multi-file path produces a module Swift sees as empty.

I cannot point at a specific SwiftPM commit — this looks like an interaction between (a) the new explicit-modules pipeline (`-fno-implicit-module-maps`, `-fno-implicit-modules`) Xcode 26 enables, (b) the umbrella-directory modulemap layout, and (c) the multi-file target's dependency-graph computation.

## Workarounds I tried (mostly didn't work)

These all failed in surprising ways and may help diagnose the underlying SwiftPM bug:

1. **Hand-written `lib/include/module.modulemap`** with explicit `umbrella header "TreeSitter.h"` — SwiftPM detects it (deletes its auto-generated copy) but **never injects `-fmodule-map-file=` into the Swift compile invocation** for that target. Other SPM dependencies in the same project all get `-fmodule-map-file=...GeneratedModuleMaps-iphoneos/X.modulemap`; only `TreeSitter` is missing from that list.
2. **Flat `lib/include/api.h`** (move out of `tree_sitter/` subdir) — SwiftPM does generate a modulemap this time but `-fno-modulemap-allow-subdirectory-search` (passed by Xcode 26 by default) breaks something downstream; same `Cannot find type` error.
3. **`OTHER_SWIFT_FLAGS = -Xcc -fmodule-map-file=$(BUILD_DIR)/../../SourcePackages/.../module.modulemap`** in the consumer project — flag does reach the swift-frontend invocation, but the module is still seen as empty.

The only thing that worked: revert `Package.swift` to 0.20-style amalgamation (`sources: ["src/lib.c"]`, drop `publicHeadersPath` and `headerSearchPath`). Patch: https://github.com/patr1ckzhu/tree-sitter/commit/9b61f80798f4e1d4e66803c8605c1a571468870b

## Proposed direction (maintainer's call)

I'm happy to send a PR but I don't want to guess at the ergonomics tradeoff. Some options:

1. **Revert to amalgamation in Package.swift only.** Same physical code, smallest diff, restores Xcode 26 compatibility today. Costs the granular per-file incremental build of the multi-file layout.
2. **Add a hand-written `lib/include/module.modulemap`.** Cleanest if Apple fixes the SwiftPM regression in a future Xcode — degrades gracefully. Risk: as documented above, didn't work for me on Xcode 26.4 (SwiftPM ignored it). Worth re-testing in case I missed something.
3. **Add a flat umbrella header (`lib/include/TreeSitter.h` that `#include`s `tree_sitter/api.h`)** alongside the subdir. Requires removing/excluding `tree_sitter/` from publicHeadersPath, which has knock-on effects.
4. **Wait for Apple.** Not great, since 0.25 has been broken on the latest Xcode for several months.

Happy to draft option 1 (or another) once you indicate which way you'd like to go.

## Downstream impact

This blocks Swift apps that consume `tree-sitter` directly via SPM from upgrading past 0.20.9 on Xcode 26, even when they want 0.25+'s parse-speed improvements and cancellation API. The amalgamation workaround is fine as a private fork pin, but a proper fix upstream would let downstream consumers track regular releases again.

Thanks for tree-sitter — much appreciated.

**Comment by clason** [comment]
PR welcome; nobody here uses the Swift bindings. Option 1, please -- we want to keep the non-core build impact to the absolute minimum. (Removing the file and punting to swift-tree-sitter is also an option.)

**Comment by patr1ckzhu** [comment]
Thanks for the quick response. Opened #5524 with Option 1 — happy to adjust the diff if needed.

**Comment by clason** [comment]
**Resolution:** We do not want to distribute unmaintained files that duplicate `swift-tree-sitter` functionality. That file should be removed in favor of depending on `swift-tree-sitter`. (If that requires fixes, help is surely appreciated. But note that this is not a core project maintained by us.)
