### ISSUE TITLE
CLI compilation error introduced by b661050a61c1c318acca2309003fc4e5f0905b58

### ISSUE THREAD

**Issue by ahlinc** [tree-sitter/tree-sitter#919]
## Error
Linker produces a huge error output that contains many complains about undefined symbols.
Bellow is an excerpt of the end of the output:
```
/tmp/tree-sitter.debug.il3ad/lib/src/./tree.c:14: undefined reference to `ts_record_malloc'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /tmp/tree-sitter.debug.il3ad/lib/src/./tree.c:20: undefined reference to `ts_record_calloc'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /tmp/tree-sitter.debug.il3ad/target/debug/deps/libtree_sitter-99382a6ca8df91d7.rlib(lib.o): in function `ts_tree_delete':
/tmp/tree-sitter.debug.il3ad/lib/src/./tree.c:37: undefined reference to `ts_record_free'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /tmp/tree-sitter.debug.il3ad/lib/src/./tree.c:38: undefined reference to `ts_record_free'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /tmp/tree-sitter.debug.il3ad/lib/src/./tree.c:39: undefined reference to `ts_record_free'
collect2: error: ld returned 1 exit status
```
If to revert the https://github.com/tree-sitter/tree-sitter/commit/b661050a61c1c318acca2309003fc4e5f0905b58 commit everything compile and work fine.

### Environment
```
# cc --version
cc (Gentoo 9.3.0-r2 p4) 9.3.0
# cargo -V
cargo 1.49.0 (d00d64df9 2020-12-05)
```

The same issue was with GCC 11 also.

### Steps to reproduce the error
1. Checkout fresh tree-sitter repo.
2. Inside of repo root folder:
```
make -j
cargo b
```

### Extra notes
Bellow is a shell script that was used to identify the root cause, it uses `git bisect` to automatically run several compilation attempts until the bad commit has been identified.
```
#!/bin/bash

set -eo pipefail

git clone https://github.com/tree-sitter/tree-sitter tree-sitter.$(mktemp -u debug.XXXXX)
cd $_

git bisect start
git bisect bad origin/master
git bisect good 0.18.0
git bisect run bash -c "git log -1; git clean -fdx && make -j && cargo b"
git log -1
git checkout master
git revert --no-edit refs/bisect/bad
git clean -fdx
make -j && cargo b
git bisect reset

git log --oneline --graph --decorate -10
```

**Comment by maxbrunsfeld** [comment]
I can't reproduce this on macOS, and it doesn't seem to happen on our linux CI, although maybe that's because we're compiling in release mode instead of debug. Do you see this if you run `cargo build --release`? Also, could you share a file containing the full output?

**Comment by ahlinc** [comment]
I was able to reproduce it on macOS inside of Docker with latest Ubuntu image by the following command:
```
docker run -it ubuntu:latest bash -c "
apt-get update; DEBIAN_FRONTEND=noninteractive apt-get -yq install git make gcc cargo;
git clone https://github.com/tree-sitter/tree-sitter; cd tree-sitter;
cargo b;
bash
"
```
Regarding `cargo build --release` on the Linux, I've checked and there is no problem, so the issue affects only debug builds.
I've attached full error log how I got it inside of the docker container on macOS produced by above command: [error.txt](https://github.com/tree-sitter/tree-sitter/files/5961644/error.txt)

**Comment by maxbrunsfeld** [comment]
The reason for the change in b661050a61c1c318acca2309003fc4e5f0905b58 is that *before* that commit, we would get errors in our GH Actions Ubuntu CI when running `cargo test`, due to *multiple* definitions of those symbols. So we can't just revert that commit.

A **current workaround** for doing debug builds is to opt into Cargo's newer feature resolver:

```
cargo -Z features=dev_dep build
```

Without that flag, Cargo does not seem to handle `features` specified in `dev-dependencies` correctly. It enables those features (which should be only enabled in tests) for debug builds as well.

The weird thing is, even with that :point_up: problem, this error shouldn't occur, because we *always* define those symbols. In tests, they are defined in [allocations.rs](https://github.com/tree-sitter/tree-sitter/blob/master/cli/src/tests/helpers/allocations.rs) and in non-test builds they are defined in [`allocation_stubs.rs`](https://github.com/tree-sitter/tree-sitter/blob/master/cli/src/allocations_stubs.rs). It's a real mystery to me why test builds *work*, but non-test builds don't.

**Comment by ahlinc** [comment]
@maxbrunsfeld thank you for useful workaround, it helps.

**Comment by dcreager** [comment]
I've been able to diagnose this, and I think I know what the fix should be, but haven't had a chance to code up the fix yet.  The mystery to solve is how it works when you build via `cargo build --tests` but not via `cargo build`.  This is a longish post but I wanted to record the steps I took to diagnose.

First, I wanted to see the specific linker commands that cargo/rustc issue.  In the failing case, we're lucky, because rustc will print out the failed linker command:

```
$ cargo build
   Compiling tree-sitter-cli v0.18.2 (/home/dcreager/git/tree-sitter/cli)
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" [quite a lot of nonsense]
```

But there's no easy way to get the linker command for a successful build.  So I quickly changed `ts_record_malloc` to `ts_record_mooloc` (i.e., any name that I knew wouldn't be defined :cow:) and was able to get the linker command for the otherwise successful `cargo build --tests` invocation:

```
$ cargo build --tests
   Compiling tree-sitter-cli v0.18.2 (/home/dcreager/git/tree-sitter/cli)
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" [a different list of nonsense]
```

In both cases, the "nonsense" is a list of ~350 libraries and object files that will all get linked together into the final result.  Going through each list, **for both builds** I was able to find an input file that defines `ts_record_free` and friends:

_From the successful build:_

```
$ nm -C tree_sitter_cli-49e1a6935f06d29b.268zk9wlxsolc1b0.rcgu.o | grep ts_record
0000000000000000 T ts_record_calloc
0000000000000000 T ts_record_free
0000000000000000 T ts_record_malloc
0000000000000000 T ts_record_realloc
```

_From the failed build:_

```
$ nm -C libtree_sitter_cli-d36e67997e083264.rlib | grep -B 6 ts_record
tree_sitter_cli-d36e67997e083264.2avn8zsnclfwsx1o.rcgu.o:
                 U calloc
                 U free
                 U malloc
                 U realloc
0000000000000000 V __rustc_debug_gdb_scripts_section__
0000000000000000 T ts_record_calloc
0000000000000000 T ts_record_free
0000000000000000 T ts_record_malloc
0000000000000000 T ts_record_realloc
```

For the failed build, it's important to realize that an `.rlib` file is just an archive file (more typically seen with a `.a` extension) produced by `ar`.  For reasons we'll see in a bit, I wanted to see which member of that archive contains the definitions.

At this point, we know that `ts_record_free` **is getting built in both cases**, but we don't yet know why we're seeing linker errors in one case but not the other.

Next step is to use the `--trace` option to tell `ld` to explicitly print out the list of files and archive members that it includes in the final linked result.  (This involved copy/pasting the "list of nonsense" output line from the log files above, and adding `-t -t` to the beginning.)

_From the successful build:_

```
$ "cc" -t -t [copy/pasted nonsense]
[snip]
/home/dcreager/git/tree-sitter/target/debug/deps/tree_sitter_cli-49e1a6935f06d29b.268zk9wlxsolc1b0.rcgu.o
[snip]
```

_From the failed build:_

```
$ "cc" -t -t [copy/pasted nonsense]
[snip]
/home/dcreager/git/tree-sitter/target/debug/deps/libtree_sitter_cli-d36e67997e083264.rlib
[NO MENTION OF 2avn8zsnclfwsx1o!]
[snip]
```

In the successful case, the linker is including the `.o` file that contains the definitions.  In the failed case, the linker includes some content from the `.rlib` file containing the definitions, **but not from the specific archive member** containing the definitions.  Since that archive member isn't included in the final result, :boom: linker error!

But why? There are two facts about `ld` to consider:

1. It will look through the files in the order that they're listed.  If the file is an archive, it will look through its archive members in the order they appear in the file.  As it iterates through this list, `ld` maintains a list of _currently unresolved_ symbols.  **When looking at a specific file or archive member**, `ld` looks at the list of currently unresolved symbols, and checks whether any of them are defined in the current file/member.  If so, it marks those symbols as resolved, and decides to include the file in the final result.  If `ld` decides to skip a file, it will not change its mind, even if later files end up needing symbols defined in the file that was just skipped.  _(This is why the usual guidance is to list files so that "upstream" dependencies appear later.)_

2. `ld` will include or leave out entire files / archive members — it doesn't do anything clever to determine which particular _parts_ of a file are needed.  So if it decides to include a file, _all_ of that files symbols are now available to resolve definitions — even if _at the time `ld` decided to include the file_ it didn't realize that some of those symbols would be needed.

That means we can end up in a situation where `ld` decides to include a file that we need **coincidentally**, if the corresponding file/archive member happens to contain _other_ symbols that it can tell are needed.  Let's verify this by looking at _all_ of the symbols defined in the file/member that we've discovered:

_From the successful build:_

```
$ nm -AC tree_sitter_cli-49e1a6935f06d29b.268zk9wlxsolc1b0.rcgu.o | grep ' T '
tree_sitter_cli-49e1a6935f06d29b.268zk9wlxsolc1b0.rcgu.o:0000000000000000 T ts_record_calloc
tree_sitter_cli-49e1a6935f06d29b.268zk9wlxsolc1b0.rcgu.o:0000000000000000 T ts_record_free
tree_sitter_cli-49e1a6935f06d29b.268zk9wlxsolc1b0.rcgu.o:0000000000000000 T ts_record_malloc
tree_sitter_cli-49e1a6935f06d29b.268zk9wlxsolc1b0.rcgu.o:0000000000000000 T ts_record_realloc
tree_sitter_cli-49e1a6935f06d29b.268zk9wlxsolc1b0.rcgu.o:0000000000000000 T ts_toggle_allocation_recording
tree_sitter_cli-49e1a6935f06d29b.268zk9wlxsolc1b0.rcgu.o:0000000000000000 T <tree_sitter_cli::tests::helpers::allocations::AllocationRecorder as core::default::Default>::default
tree_sitter_cli-49e1a6935f06d29b.268zk9wlxsolc1b0.rcgu.o:0000000000000000 T tree_sitter_cli::tests::helpers::allocations::stop_recording
tree_sitter_cli-49e1a6935f06d29b.268zk9wlxsolc1b0.rcgu.o:0000000000000000 T tree_sitter_cli::tests::helpers::allocations::start_recording
tree_sitter_cli-49e1a6935f06d29b.268zk9wlxsolc1b0.rcgu.o:0000000000000000 T <tree_sitter_cli::tests::helpers::allocations::Allocation as core::cmp::PartialEq>::eq
```

_From the failed build:_

```
$ nm -AC libtree_sitter_cli-d36e67997e083264.rlib | grep 2avn | grep ' T '
libtree_sitter_cli-d36e67997e083264.rlib:tree_sitter_cli-d36e67997e083264.2avn8zsnclfwsx1o.rcgu.o:0000000000000000 T ts_record_calloc
libtree_sitter_cli-d36e67997e083264.rlib:tree_sitter_cli-d36e67997e083264.2avn8zsnclfwsx1o.rcgu.o:0000000000000000 T ts_record_free
libtree_sitter_cli-d36e67997e083264.rlib:tree_sitter_cli-d36e67997e083264.2avn8zsnclfwsx1o.rcgu.o:0000000000000000 T ts_record_malloc
libtree_sitter_cli-d36e67997e083264.rlib:tree_sitter_cli-d36e67997e083264.2avn8zsnclfwsx1o.rcgu.o:0000000000000000 T ts_record_realloc
libtree_sitter_cli-d36e67997e083264.rlib:tree_sitter_cli-d36e67997e083264.2avn8zsnclfwsx1o.rcgu.o:0000000000000000 T ts_toggle_allocation_recording
```

And there we have it!  In the failed case, the `2avn` archive member **only** contains `ts_record_free` and friends.  Cargo's linker command lists the `tree-sitter-cli` files (where `ts_record_free` is defined) _before_ the `tree-sitter` files (where they are used), which means `ld` doesn't realize that these symbols will be needed, and doesn't include the archive member in the output.

In the successful case, the `268z` file contains some other exported definitions from the `tests::helpers::allocations` module.  Those symbols are also needed, and importantly, `ld` sees that when processing this file.  So it decides to include the file, meaning the `ts_record_free` definition is available in the final result, even though `ld` couldn't see that it was needed.

The crux of the issue is that according to the `Cargo.toml` files, the `cli` crate depends on the `lib` crate, but at the level of symbol definitions, part of the `lib` crate depends on a symbol defined in the `cli` crate.  To make this work not coincidentally, we have to break the dependency cycle, probably by moving those test-related definitions up into the `lib` crate.  (I think we'll still be able to use the `allocation-tracker` feature to make sure that they aren't compiled when they're not needed for test cases.)

**Comment by maxbrunsfeld** [comment]
👏  Amazing writeup. I'll definitely use some of these approaches in future debugging.

**Comment by dcreager** [comment]
@ahlinc I think that #934 (just merged) fixes this, can you verify before I close the issue?

**Comment by ahlinc** [comment]
@dcreager I've checked and it works! Also thank you for the investigation description :rocket: I've learned a lot about the linker behavior :student:

**Comment by dcreager** [comment]
Great, glad it worked!

**Comment by ahlinc** [comment]
@maxbrunsfeld could we also add checks of debug builds to the CI?
