### ISSUE TITLE
parser.h in tree-sitter repo is different from those in tree-sitter-c and tree-sitter-cpp

### ISSUE THREAD

**Issue by genotrance** [tree-sitter/tree-sitter#315]
Running into compile issues since I presumed they were kept in sync.

```
Error: execution of an external compiler program 'gcc -c  -w -std=c11 -DUTF8PROC_STATIC -I/build/inc/treesitter/lib/include -I/build/inc/treesitter/lib/src -I/build/inc/treesitter/lib/../../utf8proc -O3 -fno-strict-aliasing  -I/nimdevel/lib -I/nimterop -o /.cache/nim/toast_r/parser.c.o /build/inc/treesitter_c/src/parser.c' failed with exit code: 1

In file included from /build/inc/treesitter_c/src/parser.c:1:0:
/build/inc/treesitter_c/src/parser.c:55036:75: error: ‘union <anonymous>’ has no member named ‘alias_sequence_id’
   [235] = {.count = 2, .reusable = true}, REDUCE(sym__type_specifier, 1, .alias_sequence_id = 1), REDUCE(sym__expression, 1),
                                                                           ^
/build/inc/treesitter/lib/include/tree_sitter/parser.h:197:9: note: in definition of macro ‘REDUCE’
         __VA_ARGS__                              \
         ^~~~~~~~~~~
```

**Comment by bfredl** [comment]
I noticed the same also, it seems #271 changed the language API https://github.com/tree-sitter/tree-sitter/pull/271/files#diff-c5153dd814796a674e77b4a283cebe84 . I suppose `tree-sitter` generator is needed to be re-run in each language repo.

**Comment by maxbrunsfeld** [comment]
Yeah, this is expected, we include that header file in the parser repositories so that the parsers can be compiled on their own. The parsers have ABI version numbers so that you can prevent accidentally using a parser with an incompatible version of the Tree-sitter library.

The Tree-sitter PR that @bfredl mentioned just landed, so it'll take some time before I update all of the language repositories. In the meantime, you probably just want to use a 0.14.x release of Tree-sitter, rather than the head of master.

**Comment by bfredl** [comment]
@maxbrunsfeld ok, that makes sense. Currently I'm just adding all the `.c` files with the same include path, as that worked initially. Later on we need to figure out some strategy to distribute further parser libraries to an existing nvim binary, anyway.

**Comment by genotrance** [comment]
I've also updated my code to build tree-sitter with its version of parser.h and the language repos with their own version. But curious what's the value of building the languages in isolation, without the main tree-sitter API?

**Comment by maxbrunsfeld** [comment]
@genotrance The intent is that for a lot of apps (e.g. Atom), the languages will be compiled and loaded as some kind of *plugin*, whereas the Tree-sitter library is included in the core application.
