### ISSUE TITLE
Tree sitter 0.25 does not compile with no_std ("std" feature disabled)

### ISSUE THREAD

**Issue by Tiggilyboo** [tree-sitter/tree-sitter#4302]
### Problem

It seems that when bumping dependencies to 0.25 there are references to std in the lib.rs:
```
Compiling tree-sitter v0.25.3
error[E0433]: failed to resolve: use of undeclared crate or module `std`
    --> /home/simon/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tree-sitter-0.25.3/binding_rust/lib.rs:1225:38
     |
1225 |             let (c, len) = D::decode(std::slice::from_raw_parts(data, len as usize));
     |                                      ^^^ use of undeclared crate or module `std`
     |
help: consider importing one of these modules
     |
10   + use crate::slice;
     |
10   + use core::slice;
     |
10   + use alloc::slice;
     |
help: if you import `slice`, refer to it directly
     |
1225 -             let (c, len) = D::decode(std::slice::from_raw_parts(data, len as usize));
1225 +             let (c, len) = D::decode(slice::from_raw_parts(data, len as usize));
     |

error[E0433]: failed to resolve: use of undeclared crate or module `std`
    --> /home/simon/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tree-sitter-0.25.3/binding_rust/lib.rs:1425:17
     |
1425 |                 std::ptr::from_ref::<AtomicUsize>(flag).cast::<usize>(),
     |                 ^^^ use of undeclared crate or module `std`
     |
help: consider importing this module
     |
10   + use core::ptr;
     |
help: if you import `ptr`, refer to it directly
     |
1425 -                 std::ptr::from_ref::<AtomicUsize>(flag).cast::<usize>(),
1425 +                 ptr::from_ref::<AtomicUsize>(flag).cast::<usize>(),
     |

error[E0599]: no method named `stop_printing_dot_graphs` found for mutable reference `&mut Parser` in the current scope
    --> /home/simon/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tree-sitter-0.25.3/binding_rust/lib.rs:1435:14
     |
1435 |         self.stop_printing_dot_graphs();
     |              ^^^^^^^^^^^^^^^^^^^^^^^^ method not found in `&mut Parser`

Some errors have detailed explanations: E0433, E0599.
For more information about an error, try `rustc --explain E0433`.
error: could not compile `tree-sitter` (lib) due to 3 previous errors
```

### Steps to reproduce

Update tree_sitter to 0.25 in Cargo.toml in a no_std project:
```
[dependencies]
tree-sitter = { version = "0.25", default-features = false, features = [] }
```

### Expected behavior

Builds without std

### Tree-sitter version (tree-sitter --version)

0.25.3

### Operating system/version

Arch Linux
