### ISSUE TITLE
web-tree-sitter fails to load in the browser

### ISSUE THREAD

**Issue by tmr232** [tree-sitter/tree-sitter#4274]
### Problem

I am currently trying to update my code to use web-tree-sitter 0.25.3 (see https://github.com/tmr232/function-graph-overview/pull/116).

It now works well in Bun, but fails in the browser with the following error:

```
wasm streaming compile failed: LinkError: import object field 'emscripten_get_now' is not a Function tree-sitter.mjs:515:10
    instantiateAsync tree-sitter.mjs:515
    createWasm tree-sitter.mjs:579
    Module2 tree-sitter.mjs:1975
    initializeBinding bindings.ts:14
    init parser.ts:109
    initializeParser vite.ts:7
    parsers vite.ts:14
    initParsers vite.ts:17
    getFunctionByLine App.svelte:92
    createGitHubCFG App.svelte:176
    createCFG App.svelte:203
    render App.svelte:217
    create_fragment App.svelte:285
    init Component.js:148
    App App.svelte:546
    createProxiedComponent svelte-hooks.js:341
    ProxyComponent proxy.js:242
    Proxy<App> proxy.js:349
    <anonymous> main.js:4
```

My code is following [these instructions](https://www.npmjs.com/package/web-tree-sitter#loading-the-wasm-file) to load and initialize web-tree-sitter, and it works with 0.23.x.

The relevant code is at https://github.com/tmr232/function-graph-overview/blob/b298ae2dcdfaf6496cf528a0662e7e6993f6e1d5/src/parser-loader/vite.ts#L7

### Steps to reproduce

```sh
git clone https://github.com/tmr232/function-graph-overview
cd function-graph-overview
bun install
bun render
```

Then navigate to http://localhost:5173/function-graph-overview/render/?github=https://github.com/tmr232/function-graph-overview/blob/b298ae2dcdfaf6496cf528a0662e7e6993f6e1d5/src/parser-loader/vite.ts%23L6 and check the devtools console.

### Expected behavior

The web-tree-sitter module loads properly, as seen in https://tmr232.github.io/function-graph-overview/render/?github=https://github.com/tmr232/function-graph-overview/blob/b298ae2dcdfaf6496cf528a0662e7e6993f6e1d5/src/parser-loader/vite.ts%23L6 , which is the version using 0.23.x.

### Tree-sitter version (tree-sitter --version)

0.25.3

### Operating system/version

Windows 11 24H2

**Comment by tmr232** [comment]
I just tested - if I manually move the `tree-sitter.wasm` file to be next to the JS file that loads it, and use `Parser.init()` with no arguments, it works, so it seems to be a problem specifically with the `locateFile` option.

**Comment by tmr232** [comment]
My apologies - it was a bug in my own code. Closing.
