### PR TITLE
build(swift)!: drop Package.swift

### LINKED ISSUE #5523: Xcode 26 / Swift 6.3: 'import TreeSitter' yields empty module (TSLanguage not in scope)
## Summary

On Xcode 26.4 (Swift 6.3, swiftlang-6.3.0.123.5), Swift consumers of the `TreeSitter` SPM product can `import TreeSitter` without error, but cannot reference any C declarations from `lib/include/tree_sitter/api.h` — `TSLanguage`, `TSInputEncoding`, `TSInput`, etc. all resolve to `cannot find type ... in scope`. Affects every release from 0.25.0 through 0.26.8 (latest as of writing); 0.20.x is fine.

The TreeSitter Clang module *is* loaded — Clang's own lookup tables contain the symbols (see "Evidence" below). The bug is in how Xcode 26's SwiftPM/build system surfaces the publicHeadersPath modulemap to Swift consumers, not in the C sources themselves. Notably, [`swift-tree-sitter`](https://github.com/tree-sitter/swift-tree-sitter)'s CI [pins `DEVELOPER_DIR: /Applications/Xcode_16.4.app`](https://github.com/tree-sitter/swift-tree-sitter/blob/main/.github/workflows/ci.yml), so the upstream Swift binding test matrix does not catch this regression.

## Environment

- Xcode 26.4 (Build 17E192)
- Swift 6.3 (`swift-frontend -version` → `swiftlang-6.3.0.123.5 clang-2100.0.123.102`)
- `swift-tools-version: 5.8` (matches `tree-sitter`'s own Package.swift)
- macOS host, both `iphoneos` and `iphonesimulator` destinations affected
- Reproduces with `xcodebuild` and Xcode UI; **does not reproduce with `swift build` CLI** (different SwiftPM code path — see "Why amalgamation works" below)

## Reproduction

```swift
// Package.swift
// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "Repro",
    products: [.library(name: "Repro", targets: ["Repro"])],
    dependencies: [
        .package(url: "https://github.com/tree-sitter/tree-sitter", exact: "0.26.8"),
    ],
    targets: [
        .target(name: "Repro", dependencies: [
            .product(name: "TreeSitter", package: "tree-sitter"),
        ])
    ]
)
```

```swift
// Sources/Repro/Repro.swift
import TreeSitter
public func foo() -> UnsafePointer<TSLanguage>? { nil }
```

Build inside an Xcode project (or via `xcodebuild -resolvePackageDependencies` + `xcodebuild build`) on Xcode 26.4. `import TreeSitter` succeeds, every reference to `TSLanguage` (or any other api.h type) fails with `Cannot find type 'TSLanguage' in scope`.

## Evidence the C declarations *are* in the module

Running the same compile invocation Swift uses, but as bare Clang:

```sh
$ cat > /tmp/test.c <<EOF
#include "TreeSitter.h"   // or "tree_sitter/api.h"
TSLanguage *g_lang;
EOF
$ clang -fmodules \
    -fmodule-map-file=$(SourcePackages)/checkouts/tree-sitter/lib/include/module.modulemap \
    -I $(SourcePackages)/checkouts/tree-sitter/lib/include \
    -c /tmp/test.c -o /tmp/test.o
# succeeds, produces .o
```

Asking Swift's frontend to dump the ClangImporter lookup table:

```sh
$ swift -Xfrontend -dump-clang-lookup-tables -Xcc -fmodule-map-file=... test.swift
...
<<TreeSitter lookup table>>
  TSLanguage:
    TU: TSLanguage
  TSLanguageMetadata:
    TU: TSLanguageMetadata, TSLanguageMetadata
    TSLanguageMetadata: major_version
    ...
```

`TSLanguage` appears in the lookup table (TU = top-level translation unit). Yet Swift typecheck still emits `Cannot find type 'TSLanguage' in scope` — `import TreeSitter` resolves the module name but exposes nothing.

## Why 0.20.x works on Xcode 26 but 0.25+ does not

The relevant `Package.swift` diff:

| | 0.20.9 | 0.25/0.26 |
|---|---|---|
| `sources` | `["src/lib.c"]` (single amalgamation file that `#include`s every other .c) | `["src"]` (multi-file) |
| `publicHeadersPath` | default (= `"include"`) | `"include"` (explicit) |
| `cSettings.headerSearchPath` | none | `"src"` |

Both end up generating the same modulemap (`module TreeSitter { umbrella "lib/include" export * }`). But Xcode 26's build system handles single-source-file C targets along a different path that produces a Swift-visible module, while the multi-file path produces a module Swift sees as empty.

I cannot point at a specific SwiftPM commit — this looks like an interaction between (a) the new explicit-modules pipeline (`-fno-implicit-module-maps`, `-fno-implicit-modules`) Xcode 26 enables, (b) the umbrella-directory modulemap layout, and (c) the multi-file target's dependency-graph computation.

## Workarounds I tried (mostly didn't work)

These all failed in surprising ways and may help diagnose the underlying SwiftPM bug:

1. **Hand-written `lib/include/module.modulemap`** with explicit `umbrella header "TreeSitter.h"` — SwiftPM detects it (deletes its auto-generated copy) but **never injects `-fmodule-map-file=` into the Swift compile invocation** for that target. Other SPM dependencies in the same project all get `-fmodule-map-file=...GeneratedModuleMaps-iphoneos/X.modulemap`; only `TreeSitter` is missing from that list.
2. **Flat `lib/include/api.h`** (move out of `tree_sitter/` subdir) — SwiftPM does generate a modulemap this time but `-fno-modulemap-allow-subdirectory-search` (passed by Xcode 26 by default) breaks something downstream; same `Cannot find type` error.
3. **`OTHER_SWIFT_FLAGS = -Xcc -fmodule-map-file=$(BUILD_DIR)/../../SourcePackages/.../module.modulemap`** in the consumer project — flag does reach the swift-frontend invocation, but the module is still seen as empty.

The only thing that worked: revert `Package.swift` to 0.20-style amalgamation (`sources: ["src/lib.c"]`, drop `publicHeadersPath` and `headerSearchPath`). Patch: https://github.com/patr1ckzhu/tree-sitter/commit/9b61f80798f4e1d4e66803c8605c1a571468870b

## Proposed direction (maintainer's call)

I'm happy to send a PR but I don't want to guess at the ergonomics tradeoff. Some options:

1. **Revert to amalgamation in Package.swift only.** Same physical code, smallest diff, restores Xcode 26 compatibility today. Costs the granular per-file incremental build of the multi-file layout.
2. **Add a hand-written `lib/include/module.modulemap`.** Cleanest if Apple fixes the SwiftPM regression in a future Xcode — degrades gracefully. Risk: as documented above, didn't work for me on Xcode 26.4 (SwiftPM ignored it). Worth re-testing in case I missed something.
3. **Add a flat umbrella header (`lib/include/TreeSitter.h` that `#include`s `tree_sitter/api.h`)** alongside the subdir. Requires removing/excluding `tree_sitter/` from publicHeadersPath, which has knock-on effects.
4. **Wait for Apple.** Not great, since 0.25 has been broken on the latest Xcode for several months.

Happy to draft option 1 (or another) once you indicate which way you'd like to go.

## Downstream impact

This blocks Swift apps that consume `tree-sitter` directly via SPM from upgrading past 0.20.9 on Xcode 26, even when they want 0.25+'s parse-speed improvements and cancellation API. The amalgamation workaround is fine as a private fork pin, but a proper fix upstream would let downstream consumers track regular releases again.

Thanks for tree-sitter — much appreciated.

### PR DESCRIPTION
**Pull request by clason**
Problem: `Package.swift` build script is unmaintained and leads to build
errors.

Solution: Remove `Package.swift`; downstream tools should rely on the
swift-tree-sitter bindings (or, if they want a custom bare-metal build,
handle this in their own build scripts).

Closes #5523

### CODE REVIEW

**Comment by WillLillis** [comment]
I may be misreading the Swift docs, but I believe deleting this file will cause the downstream swift-tree-sitter bindings to fail because they rely on consuming tree-sitter core as a swift package. Given that swift-tree-sitter is already broken though (judging by the discussion in https://github.com/tree-sitter/tree-sitter/pull/5524), I think it seems reasonable to remove this for now. swift-tree-sitter can either move to depending on the C-lib directly, or we can reintroduce this file when someone with the know-how has a chance to try.

**Review by WillLillis — APPROVED** [review]

**Comment by clason** [comment]
swift-tree-sitter seems to be relatively actively but not seriously maintained (their `Package.swift` is still stuck on 0.25.5...). So that project looks like it needs a general renovation, as part of which it can (hopefully) work around the dropped file (by including what's necessary in their build scripts).

@mattmassicotte

**Comment by mattmassicotte** [comment]
Deleting this package file will break downstream dependencies that try to pull in tags after this is merged. You will not break any packages that are pinned to existing tags, which SwiftTreeSitter does. I was not in favor of adding a Package.swift in the first place, so I'm looking forward to this being removed.

SwiftTreeSitter is stuck on an older version because it depends on a runtime API that was removed in more recent versions. I cannot update to 0.26+ without putting in some work, and I'm not yet sure how complex the need changes will be.

I was intending on tackling the version upgrade at the same time as switching back to a git-based dependency.

**Comment by clason** [comment]
Thank you, that is very helpful (and I didn't mean to throw any shade; my wording was ill-chosen)!

And, yes, that would be a breaking change in 0.27 -- which, as a zerover minor version bump, is intended to be breaking. Your strategy of pinning to tags is absolutely the right one (and bindings should mirror library versioning exactly -- at least the minor version!) In the past, we have not been good about semantic versioning but we are taking this pretty seriously now (so patch releases are always safe to upgrade to, accidental regressions notwithstanding). 

It would be worth discussing what needs to be done to make this process more frictionless to the binding maintainers (who -- PSA -- are separate from the core team, even though they are under the same org). Various bindings are in various states of brokenness, and that is... not great. At the same time, we cannot centralize more responsibility in the core project, especially for languages nobody here is using.

**Comment by clason** [comment]
(Merging this now since we all are agreed here, but this need not shut down the discussion.)

**Comment by mattmassicotte** [comment]
No worries!

Why do you think it is important for bindings to match runtime versions? The runtime version *typically* only matters to the bindings internals, it seems like it should not actually make a difference to binding consumers. Or are you worried about parser ABI compatibility?

**Comment by clason** [comment]
Oh, it absolutely matters to consumers due to breaking _API_ changes! (As well as other behavior changes, which may be beneficial or not.) Of course, ABI compatibility matters, too, because of upper and lower bounds.

It bears repeating explicitly: We do **not** intend different minor versions of tree-sitter (lib) to be interchangeable! Only patch versions are (meant to be) pure bug fixes and should be always safe to update. (So if you have "0.26 bindings", these should work with any 0.26.x tag without changes.)

It is therefore very important for consumers to have full control over the library (minor) version, and that means that -- if they access it through bindings -- the bindings need to pass this through. Of course, details may vary: depending on the language and the structure of the bindings, they may depend explicitly on tree-sitter in their manifest in addition to the bindings, or they may only pull in the bindings and then have to rely on _that_ pulling in the correct lib. 

So if you move back to tracking git rather than individual tags, you should follow the corresponding release branch instead of `master`.

**Comment by mattmassicotte** [comment]
Hmm, perhaps SwiftTreeSitter is atypical of other bindings then? It does not expose the runtime's API, but instead an API of its own. The consumers of SwiftTreeSitter are completely unaffected by the runtime and with very little exception do not need to even be aware of it.

So, for example, when I complete the migration from 0.25 to 0.27, I intend on there being zero source compatibility issues for SwiftTreeSitter clients.

I will move back to tracking a branch. But I still do not see a technical reason to mirror the runtime library's version.

**Comment by clason** [comment]
Sorry, but I don't understand: If your bindings internally make use of new (C-lib) API introduced in 0.27, how can they work with a 0.25 library (e.g., system-wide distro installation)? And vice versa (as is the case!) if an API is removed, bindings based on the 0.25 state of the API will not work with 0.27?

(It's also a matter of clearly signaling to consumers and users about the compatibility matrix -- which is complex enough for tree-sitter as it is, due to its many moving parts...)

**Comment by mattmassicotte** [comment]
SwiftTreeSitter does not support linking with externally-installed dylibs for the runtime. It must be linked statically as part of the SwiftPM build process. That's how it works today, and also how it works for all consumers of the current (but now just removed) Package.swift implementation.

This is less true for the parsers themselves. SwiftTreeSitter supports most possible configurations. However, the vast majority of consumers (myself included) rely on static linking to make sure the final artifact is deployable to users in a way that is independent of what they might have installed.

**Comment by clason** [comment]
That's good :) My point is that it would be helpful (for the wider tree-sitter ecosystem) to be _very_ public about which version of the library is linked (and, ideally, have some quality control).

**Comment by mattmassicotte** [comment]
Via the package dependency statement, in its Package.swift, which is currently set to "0.25.x". Most users (and I suspect virtually all) use the same technique for managing parser versions. Historically, parser version matters to consumers much more than runtime, since SwiftTreeSitter exists to abstract the runtime anyways, and parsers tend to impact the end user experience a lot more.

I think I understand your point, and I do not disagree! However, if I make a material change to SwiftTreeSitter that does *not* involve changing the runtime version, I must change the version. So, keeping it in lock-step actually presents a technical challenge for me.

Thinking more: I don't think it is feasible for me to have SwiftTreeSitter match the runtime version.

**Comment by clason** [comment]
Yeah, I agree. (I was exactly in the same boat regarding parser versioning, which used to be coupled to the main lib version.)

My thinking was to just mirror the minor version (e.g., 0.26) and leave the patch version to be bumped independently. But I guess that would not necessarily work either. Anyway, just a suggestion; as long as the compatibility is made clear in some way, that's fine.
